remote_theme  : "mmistakes/minimal-mistakes"
remote_theme             : "mmistakes/minimal-mistakes"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Minimal Mistakes"
title_separator          : "-"
name                     : &name "Michael Rose" # &name is a YAML anchor which can be *referenced later
description              : &description "A flexible Jekyll theme for your blog or site with a minimalist aesthetic."
url                      : https://mmistakes.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/minimal-mistakes" # the subpath of your site, e.g. "/blog"
repository               : "mmistakes/minimal-mistakes"
